USE [master]
GO
/****** Object:  Database [BlogSharp2025]    Script Date: 27-10-2025 09:48:15 ******/
CREATE DATABASE [BlogSharp2025]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogSharp2025', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BlogSharp2025.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlogSharp2025_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BlogSharp2025_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BlogSharp2025] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogSharp2025].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BlogSharp2025] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BlogSharp2025] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BlogSharp2025] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BlogSharp2025] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BlogSharp2025] SET ARITHABORT OFF 
GO
ALTER DATABASE [BlogSharp2025] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BlogSharp2025] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BlogSharp2025] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BlogSharp2025] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BlogSharp2025] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BlogSharp2025] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BlogSharp2025] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BlogSharp2025] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BlogSharp2025] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BlogSharp2025] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BlogSharp2025] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BlogSharp2025] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BlogSharp2025] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BlogSharp2025] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BlogSharp2025] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BlogSharp2025] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BlogSharp2025] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BlogSharp2025] SET RECOVERY FULL 
GO
ALTER DATABASE [BlogSharp2025] SET  MULTI_USER 
GO
ALTER DATABASE [BlogSharp2025] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BlogSharp2025] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BlogSharp2025] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BlogSharp2025] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BlogSharp2025] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BlogSharp2025] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BlogSharp2025', N'ON'
GO
ALTER DATABASE [BlogSharp2025] SET QUERY_STORE = ON
GO
ALTER DATABASE [BlogSharp2025] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BlogSharp2025]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 27-10-2025 09:48:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[PasswordHash] [nvarchar](100) NOT NULL,
	[BlogTitle] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BlogPost]    Script Date: 27-10-2025 09:48:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogPost](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[TextBody] [nvarchar](max) NOT NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[FK_Author_Id] [int] NOT NULL,
 CONSTRAINT [PK_BlogPost] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BlogPost]  WITH CHECK ADD  CONSTRAINT [FK_BlogPost_Author] FOREIGN KEY([FK_Author_Id])
REFERENCES [dbo].[Author] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BlogPost] CHECK CONSTRAINT [FK_BlogPost_Author]
GO
USE [master]
GO
ALTER DATABASE [BlogSharp2025] SET  READ_WRITE 
GO
